#!/usr/bin/env sh

# Learn more https://component-model.bytecodealliance.org/language-support/javascript.html#running-a-component-from-javascript-applications-including-the-browser

./scripts/build-wasi

rm -rf target/js-transpile

jco transpile \
  target/wasm32-wasip1/release/nana.wasm \
  -o target/js-transpile

echo 'const { run } = await import("./nana.js");run.run();' > target/js-transpile/run.js
echo 'const { nana } = await import("./nana.js");console.log(nana.evaluate("[1 2 3]"));' >> target/js-transpile/run.js

pushd target/js-transpile
node run.js
popd

rm -rf repl/src/js-transpile
cp -R target/js-transpile repl/src