#!/usr/bin/env sh

# Learn more https://component-model.bytecodealliance.org/language-support/javascript.html#running-a-component-from-javascript-applications-including-the-browser

./scripts/build-wasi

rm -rf target/js-transpile

jco transpile \
  target/wasm32-wasip1/release/nana.wasm \
  -o target/js-transpile

echo 'const { run } = await import("./nana.js");run.run();' > target/js-transpile/run.js
echo 'const { nana } = await import("./nana.js");console.log(nana.evaluate("[1 2 3]"));' >> target/js-transpile/run.js

pushd target/js-transpile
node run.js
popd

rm -rf repl/src/js-transpile
cp -R target/js-transpile repl/src

cp examples/learn_x_in_y_minutes.nana repl/public/

# Build production version of the repl
cd repl
npm run build
cd ..

# Copy the built repl to docs/ for GitHub Pages
rm -rf docs/repl
mkdir -p docs/repl
cp -R repl/dist/* docs/repl/

echo "Production build completed and copied to docs/repl"